In [2]:
#标量由只有一个元素的张量组成
import torch
x = torch.tensor([3.9])
y = torch.tensor([4.8])
x + y, x * y, x / y, x**y
#向量视为标量组成的列表
x = torch.arange(4)
x
#通过张量的索引来访问任一元素

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [4]:
#访问张量的长度
len(x)

4

In [5]:
#只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

In [6]:
#指定分量m,n创建m*n矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
#访问矩阵转置
A.T


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B
#对称矩阵

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
#对称矩阵转置和原矩阵相等
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
#张量
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
#两个相同形状的张量，通过二元运算，不改变各自的形状
A = torch.arange(20,dtype=torch.float32).reshape(5, 4)
B =A.clone()#分配新的内存，将A的副本分配给B
A, A + B



(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
#矩阵按元素相乘，hadamard product
A, B, A*B


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [13]:
#张量加、乘一个标量不改变张量的形状（dim不变）
a = 5
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a*X).shape

(tensor([[[ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]],
 
         [[17, 18, 19, 20],
          [21, 22, 23, 24],
          [25, 26, 27, 28]]]),
 torch.Size([2, 3, 4]))

In [14]:
#计算矩阵的元素和
x =torch.arange(24).reshape(2, 3, 4)
x, x.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor(276))

In [15]:
A, A.shape, A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

In [16]:
#沿着行对矩阵求和，沿着列对矩阵求和
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape


(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [17]:
A_sum_axis1 =A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [18]:
#沿着行和列求和即为对矩阵求和
A.sum(axis = [0, 1])


tensor(190.)

In [19]:
A.mean(), A.sum(), A.numel()
#mean()为求平均值函数， sum()为求和函数， numel()为求元素个数函数


(tensor(9.5000), tensor(190.), 20)

In [20]:
#沿行求和，沿列求和，降低dim
A.mean(axis=0), A.mean(axis=1),A.shape

(tensor([ 8.,  9., 10., 11.]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]),
 torch.Size([5, 4]))

In [21]:
#计算矩阵求和|平均值，保持dim不变(上述方法会导致dim(3)矩阵->dim(2)矩阵)
sum_A = A.sum(axis=1, keepdims=True)
sum_A
sum_A.shape


torch.Size([5, 1])

In [22]:
#broadcasting mechanism 将A除以sum_A
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [23]:
#某个轴计算A的累计总和
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

In [24]:

#作两个向量的点积
x = torch.tensor([1.0, 2, 3, 4])
y =torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)


(tensor([1., 2., 3., 4.]), tensor([1., 1., 1., 1.]), tensor(10.))

In [25]:
#利用hadamard product表示向量的dot product
torch.sum(x * y)


tensor(10.)

In [26]:
#矩阵乘以向量
A.shape, x.shape, torch.mv(A,x),torch.mv(A, x).shape



(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 20.,  60., 100., 140., 180.]),
 torch.Size([5]))

In [27]:
#矩阵乘以矩阵（matrix multiplication）
#写作mm
#若干矩阵*列向量的拼接
B = torch.ones(6, 5)
B, A, torch.mm(B,A)

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[40., 45., 50., 55.],
         [40., 45., 50., 55.],
         [40., 45., 50., 55.],
         [40., 45., 50., 55.],
         [40., 45., 50., 55.],
         [40., 45., 50., 55.]]))

In [28]:
#L2范数是向量元素平方和的平方根（勾股定理的推广）
#针对向量而言
u = torch.tensor([3.0,-4.0])
torch.norm(u)


tensor(5.)

In [29]:
#L1范数，表示为向量的绝对值之和
torch.abs(u).sum()


tensor(7.)

In [30]:
#Frobenius norm
#相当于l2范数的推广
torch.norm(torch.ones(20,5))

tensor(10.)

In [36]:
wer = torch.tensor([1.0, 1])
torch.norm(wer)


tensor(1.4142)